### ISSUE TITLE
[BUG] Wifi Network not listed

### ISSUE THREAD

**Issue by erwann17** [KlipperScreen/KlipperScreen#1402] opened 2024-06-13 15:18 UTC
### What happened?

Hello
 I have a problem with Network Screen on Clipper Screen. When I open it, I don't see any wifi network appearing, whereas when I run nmtui I can see my network

![image](https://github.com/KlipperScreen/KlipperScreen/assets/146946050/de51ea89-ecdd-4f96-9ad2-b469dcc6b3ca)

### What did you expect to happen instead?

I would like to see my wifi connection

### How to reproduce this bug?

 I have a problem with Network Screen on Clipper Screen. When I open it, I don't see any wifi network appearing, whereas when I run nmtui I can see my network

### Log output

[klippy log.zip](https://github.com/user-attachments/files/15822847/klippy.log.zip)

**Comment by technical50** [comment] 2024-06-17 09:30
Try to re-install klipper screen using tool named with "Kiauh" it will ask you using network manager during install select "yes"

**Comment by erwann17** [comment] 2024-06-17 09:34
Hello I reinstalled klipper, before installing klipperscreen via kihau I can see my wifi network and once klipper screen is installed I don't see it anymore following the last update

**Comment by cuihuir** [comment] 2024-06-17 09:51
![image](https://github.com/KlipperScreen/KlipperScreen/assets/72551495/a218d7d7-851e-40b2-aa41-2773c4f6bbcb)
I fount the root cause of the issue. It's mainly caused by the privilege of network manager，update to the latest version and reinstall by kiah can solve it. But if it's still not work , try to fix it by yourself by modify the pkla files of your system. In the meanwhile of installing by kiah, it creates two pkla in direction "/etc/polkit-1/localauthority/50-local.d/" "org.freedesktop.NetworkManager.*" is to give the privileges of network.
![image](https://github.com/KlipperScreen/KlipperScreen/assets/72551495/af670e6b-1a7c-4938-aa05-afb63fce6d33)

you can try to add "org.freedesktop.NetworkManager.*" to the two files( usually needed).
Last try "nmcli general permissions" to show the permissions of the current user, if all the permission valus is "YES", all the problems resolved!
Before:
![image](https://github.com/KlipperScreen/KlipperScreen/assets/72551495/013c6b0a-c39a-4966-9ae7-182af7e2cbee)
After:
![image](https://github.com/KlipperScreen/KlipperScreen/assets/72551495/4e67a2ab-6b6f-4168-bd16-43bb7b0d55a1)

**Comment by cuihuir** [comment] 2024-06-17 09:53
> Hello I reinstalled klipper, before installing klipperscreen via kihau I can see my wifi network and once klipper screen is installed I don't see it anymore following the last update

https://github.com/KlipperScreen/KlipperScreen/issues/1402#issuecomment-2172922686

**Comment by erwann17** [comment] 2024-06-17 09:54
thank you, I'll try this

**Comment by erwann17** [comment] 2024-06-17 10:27
i don't have acces to "/etc/polkit-1/localauthority/50-local.d/"

**Comment by cuihuir** [comment] 2024-06-17 10:29
try "sudo "

**Comment by erwann17** [comment] 2024-06-17 10:32
![image](https://github.com/KlipperScreen/KlipperScreen/assets/146946050/a6a12b37-c051-413f-a889-5804a115dae7)

**Comment by cuihuir** [comment] 2024-06-17 10:34
emmm... sudo is the command to level up privilege temporary to root, so need a real command after sudo. like sudo cd /x/x/x etc...

**Comment by erwann17** [comment] 2024-06-17 10:39
yes I know but the system tells me that I don't have permission to access the file

**Comment by erwann17** [comment] 2024-06-17 10:42
sorry I'm starting with linux and I don't master all the basics

**Comment by erwann17** [comment] 2024-06-17 10:50
i take nmcli general permissions

![image](https://github.com/KlipperScreen/KlipperScreen/assets/146946050/d8f1a031-9beb-46b4-ae2b-eb82b47a901f)

**Comment by cuihuir** [comment] 2024-06-17 10:52
And does the wifi scaning work good?

**Comment by erwann17** [comment] 2024-06-17 10:52
Here are the results even though I didn't touch anything

**Comment by erwann17** [comment] 2024-06-17 10:53
the wifi scan runs continuously but doesn't show me anything

**Comment by alfrix** [comment] 2024-06-21 02:38
logfile of klipper are not valid for klipperscreen

**Comment by erwann17** [comment] 2024-06-21 05:57
[logs-20240621-075711.zip](https://github.com/user-attachments/files/15923348/logs-20240621-075711.zip)

**Comment by alfrix** [comment] 2024-06-21 20:58
looking at the logs your network is marked as "unavailable", and that may cause ks from working properly,
made some changes([3d75372](https://github.com/KlipperScreen/KlipperScreen/commit/3d7537216165641e33fec6c8ac284c1d2f6b3c45)) to catch the error and at least throw a popup, and a request reload, it's unknown to me if the condition is transitory or not, test after the changes

**Comment by erwann17** [comment] 2024-06-22 08:35
Hello

No change except for a message when searching

unexepted error: Scanning not allowed while unavailable

**Comment by alfrix** [comment] 2024-07-20 20:40
from what i can gather the "unavailable" status can be caused by many things, the most common would be invalid permissions as [cuihuir](https://github.com/cuihuir) mentioned, or conflicting services (like having wpa_supplicant running), none of the cases point to a klipperscreen issue, ks will only work if networkmanager works (try with nmcli or other nmtui) so there is no fix from the application itself, this needs the os needs to be configured to work with nm or it will not work

**Closed by alfrix** 2024-07-20 20:40 UTC
Labels: bug

**Comment by SurfSound** [comment] 2024-08-31 13:49
As there is everything ok with an older version of klipperscreen and the issue only occures after the update it is very likely that the issue is caused by klipperscreen
