### ISSUE TITLE
[BUG] Memory leak with Android tablet using WiFi

### ISSUE THREAD

**Issue by HitLuca** [KlipperScreen/KlipperScreen#1530] opened 2024-12-31 11:13 UTC
### What happened?

Today my printer crashed due to a timer too close error while idle, nothing printing and no other stuff running. After checking the resources usage on the host I noticed that KlipperScreen was using almost 80% of my 1GB of RAM, plus all the available swap space (this I am not 100% sure but looks like it). I know that sometimes KlipperScreen could have memory leaks when using an Android phone and ADB, but my launch script uses WiFi. What could be the issue here?

<img width="1205" alt="Screenshot 2024-12-31 at 11 52 08" src="https://github.com/user-attachments/assets/0d158570-1009-48bf-9f5f-2553e5570832" />

### What did you expect to happen instead?

Host wouldn't crash :)

### How to reproduce this bug?

Leave the printer running for a while, the tablet running xsdl server was locked (screen off)

### Additional information:

Logs are filled with a `RuntimeError`, which seems to reboot KlipperScreen?

```
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
2024-12-30 11:01:40,536 [screen.py:main()] - Failed to initialize window
```

the last timestamp in the logs is almost 12 hours old though, so I am not positive it's actually what caused the issue

### Log output

[KlipperScreen logs.zip](https://github.com/user-attachments/files/18281029/Archive.zip)

**Comment by alfrix** [comment] 2024-12-31 21:32
probably crashes due to the fact that no screen is attached, the service is restarting but some memory leak is happening.

let me start with "solutions":

install earlyoom `sudo apt install earlyoom`, it will kill the process if the memory usage reaches unsafe values, it will save your prints

your can also try to use the VNC route, i briefly tested it and it seemed better to me.

lastly i want to say that i do not recommend this method of running Klipperscreen, the info it's provided as is with the warnings about the leak clearly stated, i do not plan to fix it since i do not use this method at all, i'm rarely using the printers at this point,

closing as duplicate of #862

**Closed by alfrix** 2024-12-31 21:32 UTC
Labels: bug
