### ISSUE TITLE
[BUG] Internal error during connect: cannot import name signature

### ISSUE THREAD

**Issue by h3rm** [KlipperScreen/KlipperScreen#1373] opened 2024-05-24 02:31 UTC
maybe you can close the ticket. is has something to do with klipper_tmc_autotune so i opened a ticket there:
https://github.com/andrewmcgr/klipper_tmc_autotune

### What happened?

after todays update i get the error:
https://imgur.com/cBKVtbn

### What did you expect to happen instead?

normal start

### How to reproduce this bug?

update alle components via web interface

### Log output

klippy.log
Unhandled exception during connect
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 175, in _connect
    self._read_config()
  File "/home/pi/klipper/klippy/klippy.py", line 141, in _read_config
    self.load_object(config, section_config.get_name(), None)
  File "/home/pi/klipper/klippy/klippy.py", line 121, in load_object
    mod = importlib.import_module('extras.' + module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/pi/klipper/klippy/extras/autotune_tmc.py", line 3, in <module>
    from inspect import signature
ImportError: cannot import name signature
webhooks client 4119131600: New connection
webhooks client 4119131600: Client info {'program': 'Moonraker', 'version': 'v0.8.0-359-g73df63d'}

moonraker.log:

2024-05-24 04:27:00,144 [websockets.py:_handle_identify()] - Websocket 3906048952 Client Identified - Name: KlipperScreen, Version: v0.4.0-18-g0607666, Type: display
2024-05-24 04:27:00,193 [application.py:log_request()] - 404 GET /printer/info (127.0.0.1) [_TRUSTED_USER_] 8.91ms
2024-05-24 04:27:00,315 [server.py:add_log_rollover_item()] - Klipper Version: v0.12.0-205-gb6a00632-dirty
2024-05-24 04:27:00,343 [klippy_connection.py:_request_initial_subscriptions()] - Webhooks Subscribed
2024-05-24 04:27:00,347 [klippy_connection.py:_request_initial_subscriptions()] - GCode Output Subscribed
2024-05-24 04:27:00,350 [klippy_connection.py:_check_ready()] - 
Internal error during connect: cannot import name signature

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

2024-05-24 04:27:14,909 [authorization.py:_check_trusted_connection()] - Trusted Connection Detected, IP: 192.168.0.100
2024-05-24 04:27:14,912 [application.py:log_request()] - 101 GET /websocket (192.168.0.100) [_TRUSTED_USER_] 4.77ms
2024-05-24 04:27:14,913 [websockets.py:open()] - Websocket Opened: ID: 3886858616, Proxied: True, User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:126.0) Gecko/20100101 Firefox/126.0, Host Name: 192.168.0.73
2024-05-24 04:27:14,945 [websockets.py:_handle_identify()] - Websocket 3886858616 Client Identified - Name: mainsail, Version: 2.11.2, Type: web
2024-05-24 04:27:16,237 [application.py:log_request()] - 404 GET /server/files/config/.theme/maintenance.json?time=1716517635403 (192.168.0.100) [_TRUSTED_USER_] 9.91ms
2024-05-24 04:27:24,291 [machine.py:_find_public_ip()] - Detected Local IP: 192.168.0.73
2024-05-24 04:27:24,293 [webcam.py:_set_default_host_ip()] - Default public webcam address set: http://192.168.0.X

[moonraker.log](https://github.com/KlipperScreen/KlipperScreen/files/15426634/moonraker.log)
[klippy.log](https://github.com/KlipperScreen/KlipperScreen/files/15426635/klippy.log)

**Comment by alfrix** [comment] 2024-05-24 14:26
this is not related to the KlipperScreen interface closing

it seems that it has been caused by your extension/plugin not being compatible with python 2.7, i suggest installing klipper with python 3.x

**Closed by alfrix** 2024-05-24 14:26 UTC
Labels: bug

**Comment by h3rm** [comment] 2024-05-24 14:29
Maybe https://github.com/andrewmcgr/klipper_tmc_autotune/issues/174#issuecomment-2129454477 .. sry and thx
